# Change these first
owner: jpleasants # Your GitHub organization or username, where this repository lives
repo: plesk8 # The name of this repository
delay: 5000 # 5 seconds

sites:
  - name: Plesk 8
    url: https://plesk8.samitsolutions.com
    port: 8443
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: beta-search
    url: https://beta-search.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: executiveeatsnyc
    url: https://executiveeatsnyc.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: gardenroaddistributors
    url: https://gardenroaddistributors.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: midwestsleepmedicine
    url: https://midwestsleepmedicine.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Sixth Sense HI
    url: https://sixthsensehi.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: ourhealthpartner
    url: https://ourhealthpartner.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: rangolicatering
    url: https://rangolicatering.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: tandoorinrtp
    url: https://tandoorinrtp.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: thebrightfiveventure
    url: https://thebrightfiveventure.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: therangolirestaurant
    url: https://therangolirestaurant.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: wilsondigestivediseasescenter
    url: https://wilsondigestivediseasescenter.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: theairgap
    url: https://theairgap.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: triangl Ehearing
    url: https://trianglehearing.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: nukkadusa
    url: https://nukkadusa.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: synapse
    url: https://synapse-ic.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: tripler
    url: https://tripler.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: doorworkscompany
    url: https://doorworkscompany.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: originhubs
    url: https://originhubs.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: launchmorrisville
    url: https://launchmorrisville.org
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: carolinamedicalcare
    url: https://carolinamedicalcare.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: ncspices
    url: https://ncspices.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: calltoresearch
    url: https://calltoresearch.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: techlogyx
    url: https://techlogyx.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: tiecarolinas
    url: https://tiecarolinas.org
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: raidentechgroup
    url: https://raidentechgroup.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
   

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /plesk8
  logoUrl: https://samitpublic.blob.core.windows.net/download/sam-it-dots(1).png
  name: SAM IT Solutions
  theme: night
  introTitle: "**Status** page highlighting active incidents, current status of endpoints, and historical data."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  robotsText: "User-agent: * \n Disallow: /"

i18n:
  footer: ""

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
